Repository SatSea/Chislofie-Metodi, pull requests merged in 2022-02, with the labels that each got.

#6 Setup for code analysis
  .github/workflows/codeql-analysis.yml
Labels: enhancement

#7 Rename of methods files
  chord_method.py
  half_division_method.py
  tangent_method.py
Labels: enhancement

#8 Rename of files
  .vscode/launch.json
  chord_method.py
  half_division_method.py
  tangent_method.py
Labels: bug, enhancement, invalid

#9 Поправить ReadMe
  README.md
Labels: documentation

#10 Thanos
  README.md
  chord_method.py
  half_division_method.py
  tangent_method.py
Labels: enhancement
